nume = int(input('Informe um numero: '))

print('-' * 15)
print(f'1 x {nume} = {nume}')
print(f'2 x {nume} = {nume * 2}')
print(f'3 x {nume} = {nume * 3}')
print(f'4 x {nume} = {nume * 4}')
print(f'5 x {nume} = {nume * 5}')
print(f'6 x {nume} = {nume * 6}')
print(f'7 x {nume} = {nume * 7}')
print(f'8 x {nume} = {nume * 8}')
print(f'9 x {nume} = {nume * 9}')
print(f'10 x {nume} = {nume * 10}')
print('-' * 15)